update: workflows

diff --git a/.github/workflows/actionlint.yml b/.github/workflows/actionlint.yml
--- a/.github/workflows/actionlint.yml
+++ b/.github/workflows/actionlint.yml
@@ -28,11 +28,14 @@ jobs:
       - name: Actionlint Summary
         if: ${{ steps.actionlint.outputs.exit-code != 0 }}
         run: |
-          echo "Actionlint version: ${{ steps.actionlint.outputs.version-semver }} (${{
+            echo "Actionlint version: ${{ steps.actionlint.outputs.version-semver }} (${{
             steps.actionlint.outputs.version-tag }})"
-          echo "Checked files: ${{ steps.actionlint.outputs.total-files }}"
-          echo "Total errors: ${{ steps.actionlint.outputs.total-errors }}"
-          echo "Exit code: ${{ steps.actionlint.outputs.exit-code }}"
-          echo "Exit message: ${{ steps.actionlint.outputs.exit-message }}"
-          echo "Cache hit: ${{ steps.actionlint.outputs.cache-hit }}"
-          exit ${{ steps.actionlint.outputs.exit-code }}
+            echo "Checked files: ${{ steps.actionlint.outputs.total-files }}"
+            echo "Total errors: ${{ steps.actionlint.outputs.total-errors }}"
+            echo "Exit code: ${{ steps.actionlint.outputs.exit-code }}"
+            echo "Exit message: ${{ steps.actionlint.outputs.exit-message }}"
+            echo "Cache hit: ${{ steps.actionlint.outputs.cache-hit }}"
+            code=${{ steps.actionlint.outputs.exit-code || 1 }}
+            # Make sure the code is within 0-255
+            code=$((code & 255))
+            exit $code
diff --git a/.github/workflows/dockerlint.yml b/.github/workflows/dockerlint.yml
--- a/.github/workflows/dockerlint.yml
+++ b/.github/workflows/dockerlint.yml
@@ -27,8 +27,12 @@ jobs:
       - name: Hadolint Summary
         if: ${{ steps.hadolint.outputs.exitcode != 0 }}
         run: |
-          echo "Hadolint exit code: ${{ steps.hadolint.outputs.exitcode }}"
-          echo "Hadolint warnings: ${{ steps.hadolint.outputs.warnings }}"
-          echo "Hadolint errors: ${{ steps.hadolint.outputs.errors }}"
-          echo "Hadolint scanned files: ${{ steps.hadolint.outputs.files }}"
-          exit ${{ steps.hadolint.outputs.exitcode }}
+            echo "Hadolint exit code: ${{ steps.hadolint.outputs.exitcode }}"
+            echo "Hadolint warnings: ${{ steps.hadolint.outputs.warnings }}"
+            echo "Hadolint errors: ${{ steps.hadolint.outputs.errors }}"
+            echo "Hadolint scanned files: ${{ steps.hadolint.outputs.files }}"
+            code=${{ steps.hadolint.outputs.exitcode || 1 }}
+            # Ensure exit code is within 0-255
+            code=$((code & 255))
+            exit $code
+
